Document: utilmm
Title: Debian utilmm Manual
Author: <insert document author here>
Abstract: This manual describes what utilmm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/utilmm/utilmm.sgml.gz

Format: postscript
Files: /usr/share/doc/utilmm/utilmm.ps.gz

Format: text
Files: /usr/share/doc/utilmm/utilmm.text.gz

Format: HTML
Index: /usr/share/doc/utilmm/html/index.html
Files: /usr/share/doc/utilmm/html/*.html
